services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file: ./.env
    ports:
      - '8000:8000'

  nginx:
    image: nginx:stable-alpine
    volumes:
      - "${STATIC_CONTENT_PATH}:/usr/share/nginx/html:ro"
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
    command: >
      /bin/sh -c
      "envsubst '$$OPENROUTER_API_KEY' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
      && exec nginx -g 'daemon off;'"
    env_file: ./.env
    ports:
      - '80:80'
    depends_on:
      - backend